### ISSUE TITLE
Request to update image in About Us.

### ISSUE THREAD

**Issue by JustDame** [Athora190/Assignment_9#3]
Is anyone interested in updating their image on About Us?

**Comment by JustDame** [comment]
@seanc can you update to this image.  ![image](https://user-images.githubusercontent.com/76237934/104773473-1dd73300-5743-11eb-80ae-67d4a5656b05.jpeg)

**Comment by seanc** [comment]
yep!

**Comment by seanc** [comment]
fixed in #13
